spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/music?characterEncoding=utf-8&useSSL=false
    username: root
    password: admin
    #配置监控兰姐的filters，去掉后监控界面sql将无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    #最大活跃数
    maxActive: 20
    #初始化数量
    initialSize: 1
    #最大连接等待超过时间
    maxWait: 60000
    #打开PSCache，并且制定每个连接PSCatch的大小
    poolPreparedStatement: true
    maxPreparedStatementPerConnectionSize: 20
    #通过connectionProperties属性来打开mergeSql功能：慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minidle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableldleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOneBorrow: false
    testOneReturn: false
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true
#        use_sql_comments: true


  mvc:
      view:
        suffix: .jsp
        prefix: /WEB-INF/jsp/

